services:
  - type: web
    name: bellas-kitchen-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    domains:
      - api.bellaskitchen.online
    envVars:
      - key: PORT
        value: 5001

  - type: web
    name: bellas-kitchen-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    domains:
      - bellaskitchen.online
      - www.bellaskitchen.online
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
